---
version: 2
jobs:
  test:
    docker:
      - image: cimg/go:1.17
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run:
          name: Run unit tests and create coverage report
          command: make coverage
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - store_artifacts:
          path: tmp/output/coverage
          destination: raw-test-output
      - store_test_results:
          path: tmp/output/results
  lint:
    docker:
      - image: cimg/go:1.17
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-lint-v1-{{ checksum "go.sum" }}
      - run:
          name: Lint
          command: make lint
      - save_cache:
          key: go-mod-lint-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
workflows:
  version: 2
  build-workflow:
    jobs:
      - test
      - lint
